#!/bin/bash
# $Id: makeit,v 1.2 2010-09-06 13:35:53-05 annis Exp annis $
# $Source: /Users/annis/Documents/Navi/horen/RCS/makeit,v $
#
# Ah, indexing.

xelatex horen-lenavi_de
makeindex  horen-lenavi_de
xelatex horen-lenavi_de

# EOF

